### ISSUE TITLE
[Whats wrong with my config file?]

### ISSUE THREAD

**Issue by OhaDerErste** [realDragonium/Ultraviolet#9]
![Config+Terminal output](https://user-images.githubusercontent.com/77100649/167195415-daa136a4-91d5-433c-88af-c9153f6f048c.png)

**Comment by realDragonium** [comment]
The second json body (the one for the mc server config) should be in a separate file

**Comment by OhaDerErste** [comment]
in what file?

**Comment by realDragonium** [comment]
Name doesn't matter as long as it isnt `ultraviolet.json` and it should end with `.json`

**Comment by OhaDerErste** [comment]
thanks!
